<?php $this->addItemRender('default', 'sales/order_item_renderer_default', 'ordersuccesspage/renderer.phtml'); ?>
<?php $this->addItemRender('grouped', 'sales/order_item_renderer_grouped', 'ordersuccesspage/renderer.phtml'); ?>
<?php $_order = $this->getOrder() ?>
<div class="order-details">
    <h3><?php echo $this->__('Order Details'); ?></h3>
    <div class="order-actions">
        <a href="<?php echo Mage::getUrl('sales/order/print', array('order_id' => $_order->getId())); ?>"><img src="<?php echo $this->getSkinUrl('images/print-icon-osp.png'); ?>" alt="<?php echo $this->__('Print'); ?>" title="<?php echo $this->__('Print'); ?>" /></a>
        <a href="<?php echo Mage::getUrl('ordersuccesspage/ordersuccesspage/email', array('order_id' => $_order->getId())); ?>"><img src="<?php echo $this->getSkinUrl('images/mail-icon-osp.png'); ?>" alt="<?php echo $this->__('Email'); ?>" title="<?php echo $this->__('Email'); ?>" /></a>
    </div>
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getParentItem()) continue; ?>
        <div class="order-items">
            <?php echo $this->getItemHtml($_item); ?>
        </div>
        <hr/>
    <?php endforeach; ?>
</div>

<?php /*
  <table class="data-table" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">
  <col />
  <col width="1" />
  <col width="1" />
  <col width="1" />
  <col width="1" />
  <thead>
  <tr>
  <th><?php echo $this->__('Product Name') ?></th>
  <th><?php echo $this->__('SKU') ?></th>
  <th class="a-right"><?php echo $this->__('Price') ?></th>
  <th class="a-center"><?php echo $this->__('Qty') ?></th>
  <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
  </tr>
  </thead>
  <tfoot>
  <?php
  $block = $this->getLayout()->createBlock('tax/sales_order_tax')->setTemplate('ordersuccesspage/tax.phtml');
  $totals_block = $this->getLayout()->createBlock('sales/order_totals')->setTemplate('ordersuccesspage/totals.phtml')->setLabelProperties('colspan="4" class="a-right"')->setValueProperties('class="last a-right"');
  $totals_block = $totals_block->append($block);
  echo $totals_block->toHtml();
  ?>
  </tfoot>
  <?php $_items = $_order->getItemsCollection(); ?>
  <?php $_index = 0; ?>
  <?php $_count = $_items->count(); ?>
  <?php foreach ($_items as $_item): ?>
  <?php if ($_item->getParentItem()) continue; ?>
  <tbody>
  <?php echo $this->getItemHtml($_item) ?>
  <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
  <tr class="border<?php echo ($_index++ > $_count ? ' last' : '') ?>" id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
  <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
  <td class="gift-message-row" colspan="7">
  <a href="#" title="<?php echo $this->__('Close') ?>" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>');" class="btn-close"><?php echo $this->__('Close') ?></a>
  <dl class="gift-message">
  <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?></dt>
  <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?></dt>
  <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
  </dl>
  </td>
  </tr>
  <?php endif ?>
  </tbody>
  <?php endforeach; ?>
  </table>
  <script type="text/javascript">decorateTable('my-orders-table', {'tbody': ['odd', 'even'], 'tbody tr': ['first', 'last']})</script>

 */
