<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
        <ul class="<?php echo $_code ?>">
            <li <?php echo $this->getLabelProperties() ?>>
                <?php if ($_total->getStrong()): ?>
                    <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
                <?php else: ?>
                    <?php echo $this->escapeHtml($_total->getLabel()); ?>
                <?php endif ?>
            </li>
            <li <?php echo $this->getValueProperties() ?>>
                <?php if ($_total->getStrong()): ?>
                    <strong><?php echo $this->formatValue($_total) ?></strong>
                <?php else: ?>
                    <?php echo $this->formatValue($_total) ?>
                <?php endif ?>
            </li>
        </ul>
    <?php endif ?>
<?php endforeach ?>
