<div class="banner-bck">
    <img
        src="<?php echo Mage::getBaseUrl('media') . "theme/" . Mage::getStoreConfig('hero/hero_group/hero_input5') ?>"
        alt="" />
    <div class="title">
        <?php echo Mage::getStoreConfig('hero/hero_group/hero_input1'); ?>
    </div>
    <div class="sub-title">
        <?php echo Mage::getStoreConfig('hero/hero_group/hero_input2'); ?>
    </div>
    <div class="banner-link">
        <a
            href="<?php echo Mage::getStoreConfig('hero/hero_group/hero_input4'); ?>"><?php echo Mage::getStoreConfig('hero/hero_group/hero_input3'); ?>
        </a>
    </div>

</div>
